[package]
name = "port"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

description = "CLI-first Firecracker orchestration for local and cloud Linux hosts"

[[bin]]
name = "port"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
libc.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
port-agent-protocol = { path = "../port-agent-protocol" }
port-model = { path = "../port-model" }
port-runtime = { path = "../port-runtime" }

[dev-dependencies]
assert_cmd = "2.0.16"
port-guest-agent = { path = "../port-guest-agent" }
tempfile.workspace = true
