[package]
name = "port-guest-agent"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[package.metadata.dist]
dist = false

[[bin]]
name = "port-guest-agent"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
libc.workspace = true
portable-pty.workspace = true
port-agent-protocol = { path = "../port-agent-protocol" }
port-model = { path = "../port-model" }
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
vsock.workspace = true
