apiVersion: v1
kind: Config
clusters:
- cluster:
    server: http://127.0.0.1:36901
  name: demo
contexts:
- context:
    cluster: demo
    user: demo
  name: demo
current-context: demo
users:
- name: demo
  user:
    token: demo-token
